name: CI-CD-React-App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v4
        # Action Marketplace : Clone le dépôt

      # Étape 2 : Configurer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        # Action Marketplace : Configure Node.js

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Étape 4 : Exécuter les tests
      - name: Run tests
        run: npm test

      # Étape 5 : Analyse de sécurité avec CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
        # Action Marketplace : Initialise l’analyse statique

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        # Action Marketplace : Analyse les vulnérabilités

      # Étape 6 : Vérification des dépendances
      - name: Check dependencies
        uses: dependabot/fetch-metadata@v2
        # Action Marketplace : Vérifie les dépendances vulnérables

      # Étape 7 : Construire l’application
      - name: Build app
        run: npm run build

      # Étape 8 : Déployer sur Vercel
      - name: Deploy to Vercel
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        # Action Marketplace : Déploie sur Vercel
