name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE: rhzvenom/hello-world-api
  DOCKER_TAG: ${{ github.ref_name }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE:$DOCKER_TAG .

      - name: Push Docker image
        run: |
          docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:$DOCKER_TAG

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run docker-compose
        run: docker-compose -f docker-compose.yml up -d

  final_test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for server
        run: sleep 5

      - name: Check if app is up
        run: curl -f http://localhost:3000

